default_param = {
    'iwildcam':{
        'num_experts': 10,
        'expert_batch_size': 16,
        'expert_lr': 3e-5,
        'expert_l2': 0,
        'expert_epoch': 12,
        'aggregator_depth': 1,
        'aggregator_heads': 16,
        'aggregator_dropout': 0.1,
        'aggregator_pretrain_epoch': 12,
        'student_pretrain_epoch': 12,
        'batch_size': 40,
        'sup_size': 24,
        'tlr': 1e-6,
        'slr': 3e-5,
        'ilr': 3e-4,
        'epoch': 20,
        'seed': 1
    },
    'camelyon':{
        'num_experts': 5,
        'expert_batch_size': 32,
        'expert_lr': 1e-3,
        'expert_l2': 1e-2,
        'expert_epoch': 5,
        'aggregator_depth': 1,
        'aggregator_heads': 16,
        'aggregator_dropout': 0.1,
        'aggregator_pretrain_epoch': 5,
        'student_pretrain_epoch': 5,
        'batch_size': 96,
        'sup_size': 64,
        'tlr': 1e-6,
        'slr': 1e-4,
        'ilr': 1e-3,
        'epoch': 10,
        'seed': 3407
    },
    'rxrx1':{
        'num_experts': 3,
        'expert_batch_size': 75,
        'expert_lr': 1e-4,
        'expert_l2': 1e-5,
        'expert_epoch': 90,
        'aggregator_depth': 1,
        'aggregator_heads': 16,
        'aggregator_dropout': 0.1,
        'aggregator_pretrain_epoch': 90,
        'student_pretrain_epoch': 90,
        'batch_size': 123,
        'sup_size': 75,
        'tlr': 3e-6,
        'slr': 1e-6,
        'ilr': 1e-4,
        'epoch': 10,
        'seed': 1000
    },
    'fmow':{
        'num_experts': 4,
        'expert_batch_size': 64,
        'expert_lr': 1e-4,
        'expert_l2': 0,
        'expert_epoch': 30,
        'aggregator_depth': 1,
        'aggregator_heads': 16,
        'aggregator_dropout': 0.1,
        'aggregator_pretrain_epoch': 50,
        'student_pretrain_epoch': 20,
        'batch_size': 112,
        'sup_size': 64,
        'tlr': 1e-6,
        'slr': 1e-5,
        'ilr': 1e-4,
        'epoch': 30,
        'seed': 42
    }
}